erDiagram
    AIQuota ||--|{ Instant : contains
    AIUsage ||--|{ AIUsageType : contains
    AIUsage ||--|{ Instant : contains
    CreditRecord ||--|{ LocalDate : contains
    AmbassadorLeaderboardModel ||--|{ Instant : contains
    AmbassadorLeaderboardModel ||--|{ Instant : contains
    AmbassadorPointAudit ||--|{ Instant : contains
    AmbassadorProfileModel ||--|{ Instant : contains
    AmbassadorProfileModel ||--|{ AmbassadorLifecycle : contains
    AmbassadorProfileModel ||--|{ Instant : contains
    AmbassadorProfileModel ||--|{ Instant : contains
    AmbassadorProfileModel ||--|{ Instant : contains
    AmbassadorProfileModel ||--|{ Instant : contains
    AmbassadorRewardModel ||--|{ Instant : contains
    AmbassadorRewardModel ||--|{ Instant : contains
    AmbassadorSessionModel ||--|{ Instant : contains
    AmbReferralModel ||--|{ Instant : contains
    AmbReferralModel ||--|{ Instant : contains
    BadgeModel ||--|{ Instant : contains
    SwagModel ||--|{ Instant : contains
    SwagModel ||--|{ Instant : contains
    SwagModel ||--|{ Instant : contains
    Announcement ||--|{ AnnouncementStatus : contains
    Announcement ||--|{ AnnouncementType : contains
    Announcement ||--|{ AnnouncementVisibility : contains
    Announcement ||--|{ AnnouncementPriority : contains
    Article ||--|{ ArticleStatus : contains
    ArticleEvaluationLog ||--|{ ArticleEvaluationDTO : contains
    AsyncUpdateAuditLog ||--|{ Instant : contains
    ClientActAuditLog ||--|{ Instant : contains
    CourseReminderAuditLog ||--|{ Instant : contains
    CourseReminderAuditLog ||--|{ Instant : contains
    SchedulerLogModel ||--|{ Instant : contains
    SchedulerLogModel ||--|{ Instant : contains
    StripeAuditLog ||--|{ Instant : contains
    TaskRewardAuditModel ||--|{ Instant : contains
    TaskRewardAuditModel ||--|{ Instant : contains
    PermissionModel ||--|{ Instant : contains
    PermissionModel ||--|{ Instant : contains
    Login ||--|{ LoginMetaDTO : contains
    Comment ||--|{ Reaction : contains
    Comment ||--|{ Comment : contains
    Community ||--|{ CommunityPrivacy : contains
    CommunityMember ||--|{ MemberRole : contains
    Notification ||--|{ NotificationType : contains
    Post ||--|{ PostContent : contains
    Post ||--|{ PostMetrics : contains
    Post ||--|{ Reaction : contains
    Post ||--|{ LinkPreview : contains
    Report ||--|{ ReportTargetType : contains
    Report ||--|{ ReportStatus : contains
    CourseBatchModel ||--|{ InstallmentDTO : contains
    CourseBatchModel ||--|{ ModuleDTO : contains
    CourseBatchModel ||--|{ MaterialsDTO : contains
    CourseBatchModel ||--|{ QuizDTO : contains
    CourseModel ||--|{ InstallmentDTO : contains
    CourseModel ||--|{ ModuleDTO : contains
    CourseModel ||--|{ MaterialsDTO : contains
    CourseModel ||--|{ QuizDTO : contains
    CourseModel ||--|{ CourseMissedNotify : contains
    RecordedCourseModel ||--|{ BigDecimal : contains
    RecordedCourseModel ||--|{ RecModuleDTO : contains
    RecordedCourseModel ||--|{ RecordedCourseReviewDTO : contains
    RecordedCourseModel ||--|{ BigDecimal : contains
    RecordedCourseModel ||--|{ BigDecimal : contains
    RecordedCourseModel ||--|{ InstallmentDTO : contains
    TrainCompanyModel ||--|{ TeamMemberDTO : contains
    CmpPostedJobsModel ||--|{ PostedJobsDTO : contains
    CmpSocialModel ||--|{ SocialLinksDTO : contains
    StandaloneFileModel ||--|{ Instant : contains
    StandaloneFileModel ||--|{ Instant : contains
    EAffiliateCommissions ||--|{ Instant : contains
    EAffiliateLinks ||--|{ Instant : contains
    EAffiliates ||--|{ EAffiliateStatus : contains
    EAffiliates ||--|{ Instant : contains
    EAffiliates ||--|{ Instant : contains
    EAiCredits ||--|{ Instant : contains
    EAiCredits ||--|{ Instant : contains
    EAiCredits ||--|{ Instant : contains
    EAiCredits ||--|{ Instant : contains
    EAiUsage ||--|{ EAIUsageType : contains
    EAiUsage ||--|{ Instant : contains
    EAnalyticsEvents ||--|{ EAnalyticsEvent : contains
    EAnalyticsEvents ||--|{ Instant : contains
    EApiKey ||--|{ Instant : contains
    EApiKey ||--|{ Instant : contains
    EApiKey ||--|{ Instant : contains
    EAssignments ||--|{ Instant : contains
    EAssignments ||--|{ Instant : contains
    EAssignments ||--|{ Instant : contains
    EAssignmentSubmissions ||--|{ EGradingStatus : contains
    EAssignmentSubmissions ||--|{ Instant : contains
    EAssignmentSubmissions ||--|{ Instant : contains
    EAuditLog ||--|{ Instant : contains
    EBundles ||--|{ Instant : contains
    ECertificates ||--|{ Instant : contains
    ECouponRedemption ||--|{ Instant : contains
    ECoupons ||--|{ Instant : contains
    ECoupons ||--|{ Instant : contains
    ECourses ||--|{ ECourseType : contains
    ECourses ||--|{ ECourseContentType : contains
    ECourses ||--|{ ECourseLevel : contains
    ECourses ||--|{ ECourseStatus : contains
    ECourses ||--|{ ECourseValidationStatus : contains
    ECourses ||--|{ Instant : contains
    ECourses ||--|{ Instant : contains
    ECourses ||--|{ Instant : contains
    ECourseSections ||--|{ ELessons : contains
    ECourseSections ||--|{ Instant : contains
    ECourseSections ||--|{ Instant : contains
    ECreatorFinanceSettings ||--|{ PayoutMethod : contains
    ECreatorFinanceSettings ||--|{ TaxForm : contains
    ECreatorFinanceSettings ||--|{ Instant : contains
    ECreatorFinanceSettings ||--|{ Instant : contains
    ECreatorFinanceSettings ||--|{ Instant : contains
    ECreditLedger ||--|{ ECreditLedgerActionType : contains
    ECreditLedger ||--|{ Instant : contains
    EduCourseReviewLog ||--|{ Instant : contains
    EEnrollments ||--|{ Instant : contains
    EEnrollments ||--|{ Instant : contains
    EEnrollments ||--|{ Instant : contains
    EEnrollments ||--|{ Instant : contains
    EEnrollments ||--|{ Instant : contains
    EEnrollments ||--|{ Instant : contains
    EEnrollments ||--|{ ECourses : contains
    EFraudFlag ||--|{ Instant : contains
    EFraudFlag ||--|{ Instant : contains
    EGifts ||--|{ EGiftStatus : contains
    EGifts ||--|{ Instant : contains
    EGifts ||--|{ Instant : contains
    EGifts ||--|{ Instant : contains
    EGifts ||--|{ Instant : contains
    EHoldingLedger ||--|{ EBeneficiaryType : contains
    EHoldingLedger ||--|{ EHoldingStatus : contains
    EHoldingLedger ||--|{ Instant : contains
    EHoldingLedger ||--|{ Instant : contains
    EHoldingLedger ||--|{ Instant : contains
    ELearningPaths ||--|{ Instant : contains
    ELearningPaths ||--|{ Instant : contains
    ELedgerEntry ||--|{ EventType : contains
    ELedgerEntry ||--|{ EntryType : contains
    ELedgerEntry ||--|{ AccountType : contains
    ELedgerEntry ||--|{ Instant : contains
    ELessons ||--|{ ELessonType : contains
    ELessons ||--|{ Instant : contains
    ELessons ||--|{ Instant : contains
    ENotifications ||--|{ ENotificationType : contains
    ENotifications ||--|{ Instant : contains
    ENotifications ||--|{ Instant : contains
    ENotifications ||--|{ Instant : contains
    EPayouts ||--|{ EPayoutMethod : contains
    EPayouts ||--|{ EPayoutStatus : contains
    EPayouts ||--|{ Instant : contains
    EPayouts ||--|{ Instant : contains
    EPayouts ||--|{ Instant : contains
    EPayoutSchedule ||--|{ Instant : contains
    EPayoutSchedule ||--|{ Instant : contains
    EPayoutSchedule ||--|{ Instant : contains
    EProfiles ||--|{ ESocialLinksDTO : contains
    EProfiles ||--|{ EPrivacySettingsDTO : contains
    EProfiles ||--|{ ENotificationSettingsDTO : contains
    EProfiles ||--|{ Instant : contains
    EProfiles ||--|{ Instant : contains
    EQuizAttempts ||--|{ EGradingStatus : contains
    EQuizAttempts ||--|{ Instant : contains
    EQuizAttempts ||--|{ Instant : contains
    EQuizAttempts ||--|{ Instant : contains
    EQuizzes ||--|{ EQuizType : contains
    EQuizzes ||--|{ EQuestionDTO : contains
    EQuizzes ||--|{ Instant : contains
    EQuizzes ||--|{ Instant : contains
    ERefund ||--|{ RefundType : contains
    ERefund ||--|{ RefundStatus : contains
    ERefund ||--|{ Instant : contains
    ERefund ||--|{ Instant : contains
    EReports ||--|{ EReportReason : contains
    EReports ||--|{ EReportStatus : contains
    EReports ||--|{ Instant : contains
    EReports ||--|{ Instant : contains
    EReviews ||--|{ Instant : contains
    EReviews ||--|{ Instant : contains
    ESubscriptions ||--|{ ESubscriptionPlan : contains
    ESubscriptions ||--|{ ESubscriptionStatus : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESubscriptions ||--|{ Instant : contains
    ESystemSettings ||--|{ Instant : contains
    ETransactions ||--|{ EPaymentMethod : contains
    ETransactions ||--|{ EPaymentStatus : contains
    ETransactions ||--|{ Instant : contains
    ETransactions ||--|{ Instant : contains
    ETransactions ||--|{ Instant : contains
    ETrustScores ||--|{ Instant : contains
    ETrustScores ||--|{ Instant : contains
    ETrustScores ||--|{ Instant : contains
    ETrustScores ||--|{ Instant : contains
    EUser ||--|{ Instant : contains
    EUser ||--|{ Instant : contains
    EUser ||--|{ Instant : contains
    EUser ||--|{ Instant : contains
    EUserPreferences ||--|{ Instant : contains
    EUserPreferences ||--|{ Instant : contains
    EValidationReports ||--|{ EValidationBreackdownDTO : contains
    EValidationReports ||--|{ Instant : contains
    EWallet ||--|{ Instant : contains
    EWalletTransaction ||--|{ TransactionType : contains
    EWalletTransaction ||--|{ TransactionStatus : contains
    EWalletTransaction ||--|{ Instant : contains
    EWebhookEvent ||--|{ EventStatus : contains
    EWebhookEvent ||--|{ Instant : contains
    EWebhookEvent ||--|{ Instant : contains
    EWorkspaceMembers ||--|{ ERoles : contains
    EWorkspaceMembers ||--|{ Instant : contains
    EWorkspaceMembers ||--|{ Instant : contains
    EWorkspaces ||--|{ EWorkspaceType : contains
    EWorkspaces ||--|{ ESubscriptionPlan : contains
    EWorkspaces ||--|{ EWSettingsDTO : contains
    EWorkspaces ||--|{ EWProfileDTO : contains
    EWorkspaces ||--|{ Instant : contains
    EWorkspaces ||--|{ Instant : contains
    AnalyticsData ||--|{ Instant : contains
    FinAiTrainingSnapshot ||--|{ Instant : contains
    FinAssumption ||--|{ Instant : contains
    FinAuditLog ||--|{ Instant : contains
    FinBudget ||--|{ Instant : contains
    FinFinancialSnapshot ||--|{ Instant : contains
    FinPricingModel ||--|{ Instant : contains
    FinProject ||--|{ Instant : contains
    FinProject ||--|{ Instant : contains
    FinProjectMember ||--|{ ProjectRole : contains
    FinProjectMember ||--|{ Instant : contains
    FinSalesPlan ||--|{ Instant : contains
    FinScenario ||--|{ AssumptionOverride : contains
    FinScenario ||--|{ Instant : contains
    FinWorkspace ||--|{ Instant : contains
    FinWorkspace ||--|{ Instant : contains
    Scenario ||--|{ Instant : contains
    ScenarioOverride ||--|{ OverrideOperation : contains
    ScenarioOverride ||--|{ Instant : contains
    ApplicantModel ||--|{ Instant : contains
    ApplicantModel ||--|{ Instant : contains
    JobPostModel ||--|{ Instant : contains
    JobPostModel ||--|{ Instant : contains
    JobPostModel ||--|{ Instant : contains
    AICacheEntry ||--|{ Instant : contains
    UserCredits ||--|{ SubscriptionTier : contains
    UserCredits ||--|{ Instant : contains
    Goal ||--|{ Instant : contains
    Goal ||--|{ GoalType : contains
    Goal ||--|{ GoalTimeline : contains
    Goal ||--|{ Instant : contains
    Goal ||--|{ Instant : contains
    JournalEntry ||--|{ LocalDate : contains
    JournalEntry ||--|{ Instant : contains
    MoodEntry ||--|{ LocalDate : contains
    MoodEntry ||--|{ Instant : contains
    WeeklyMoodSummary ||--|{ LocalDate : contains
    WeeklyMoodSummary ||--|{ LocalDate : contains
    WeeklyMoodSummary ||--|{ Instant : contains
    LPNotification ||--|{ Instant : contains
    DailySchedule ||--|{ LocalDate : contains
    DailySchedule ||--|{ ScheduleTask : contains
    StudyPlan ||--|{ RoadmapItem : contains
    StudyPlan ||--|{ WeeklyPlan : contains
    StudyPlan ||--|{ Instant : contains
    StudyPlan ||--|{ Instant : contains
    User ||--|{ Instant : contains
    User ||--|{ Instant : contains
    UserProfile ||--|{ Instant : contains
    UserProfile ||--|{ Instant : contains
    ChatRoom ||--|{ RoomType : contains
    Message ||--|{ MessageType : contains
    Message ||--|{ Instant : contains
    UserPresence ||--|{ PresenceStatus : contains
    RecordedCoursePayment ||--|{ BigDecimal : contains
    RecordedCoursePayment ||--|{ BigDecimal : contains
    RecordedCoursePayment ||--|{ BigDecimal : contains
    RecordedCoursePayment ||--|{ BigDecimal : contains
    AmbassadorTaskProgressModel ||--|{ Instant : contains
    AmbassadorTaskProgressModel ||--|{ Instant : contains
    AmbassadorTaskProgressModel ||--|{ Instant : contains
    AmbassadorTaskProgressModel ||--|{ Instant : contains
    BadgeDefinition ||--|{ Instant : contains
    CourseCouponsModel ||--|{ private String : contains
    CourseCouponsModel ||--|{ Instant : contains
    CourseCouponsModel ||--|{ Instant : contains
    CourseCouponsModel ||--|{ Instant : contains
    CourseCouponsModel ||--|{ Instant : contains
    CourseCouponsModel ||--|{ Instant : contains
    CourseCouponsModel ||--|{ Status : contains
    CourseCouponsModel ||--|{ Instant : contains
    CourseReminderLog ||--|{ Instant : contains
    EmpCoursesModel ||--|{ CourseEnrollment : contains
    EmpCoursesModel ||--|{ RecordedCourseEnrollment : contains
    GamificationTaskModel ||--|{ Instant : contains
    QuizAttempt ||--|{ QuestionAnswer : contains
    SwagItem ||--|{ Instant : contains
    InterviewQuestionModel ||--|{ Question : contains
    InterviewQuestionModel ||--|{ Answer : contains
    Referral ||--|{ ReferralType : contains
    Referral ||--|{ ReferralStatus : contains
    Referral ||--|{ Instant : contains
    Referral ||--|{ Instant : contains
    ReferralCode ||--|{ Instant : contains
    ReferralCommission ||--|{ Instant : contains
    ReferralCommission ||--|{ Instant : contains
    ReputationEvent ||--|{ ReputationSourceType : contains
    UserBadge ||--|{ BadgeType : contains
    ResumeModel ||--|{ PersonalInfo : contains
    ResumeModel ||--|{ WorkExperience : contains
    ResumeModel ||--|{ Education : contains
    ResumeModel ||--|{ Skill : contains
    ResumeModel ||--|{ Project : contains
    ResumeModel ||--|{ Certificate : contains
    ResumeModel ||--|{ CustomSection : contains
    ResumeModel ||--|{ ResumeSettings : contains
    ResumeModel ||--|{ Instant : contains
    ResumeModel ||--|{ Instant : contains
    ResumeModel ||--|{ CustomSectionItem : contains
    SoftwareAppModel ||--|{ Instant : contains
    SoftwareAppModel ||--|{ Instant : contains
    FeatureFlag ||--|{ ESubscriptionPlan : contains
    Subscription ||--|{ ESubscriptionPlan : contains
    Subscription ||--|{ ESubscriptionStatus : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    Subscription ||--|{ Instant : contains
    SupportRequestModel ||--|{ Instant : contains
    TrackingEvent ||--|{ Instant : contains
    TrackingEvent ||--|{ Instant : contains
    EmpCertificatesModel ||--|{ EmpCertificatesDTO : contains
    EmpContactModel ||--|{ EmpContactDTO : contains
    EmpContactModel ||--|{ SocialLinksDTO : contains
    EmpEducationModel ||--|{ EmpEducationDTO : contains
    EmpExperiencesModel ||--|{ EmpExperiencesDTO : contains
    EmpFollowersModel ||--|{ EmpFollowersDTO : contains
    EmpFollowingModel ||--|{ EmpFollowingDTO : contains
    EmployeeModel ||--|{ FavJobDTO : contains
    EmpProjectsModel ||--|{ EmpProjectsDTO : contains
    EmpSkillsModel ||--|{ EmpSkillsDTO : contains
    UserActivity ||--|{ Instant : contains
