package com.talentboozt.s_backend.domains.ai_orchestration.service;

import com.talentboozt.s_backend.domains.ai_orchestration.model.AiTask;
import com.talentboozt.s_backend.domains.ai_orchestration.repository.mongodb.AiTaskRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

@Service
@RequiredArgsConstructor
public class AiOrchestratorService {
    private final AiTaskRepository aiTaskRepository;

    public AiTask submitTask(String type, Map<String, Object> inputData) {
        AiTask task = AiTask.builder()
                .type(type)
                .status("PENDING")
                .inputData(inputData)
                .provider("GEMINI") // Default provider
                .createdAt(Instant.now())
                .updatedAt(Instant.now())
                .retryCount(0)
                .build();
        
        return aiTaskRepository.save(task);
    }

    @Async
    public CompletableFuture<AiTask> processTask(String taskId) {
        AiTask task = aiTaskRepository.findById(taskId).orElseThrow();
        task.setStatus("PROCESSING");
        task.setUpdatedAt(Instant.now());
        aiTaskRepository.save(task);

        try {
            // Here we would call the actual AI provider (Gemini/OpenAI)
            // For now, we simulate success
            Thread.sleep(1500); 
            
            task.setStatus("COMPLETED");
            task.setResultData(Map.of("processed", true, "intelligence", "Generated by Talnova AI"));
            task.setCompletedAt(Instant.now());
        } catch (Exception e) {
            task.setStatus("FAILED");
            task.setErrorMessage(e.getMessage());
        }

        task.setUpdatedAt(Instant.now());
        return CompletableFuture.completedFuture(aiTaskRepository.save(task));
    }
}
