package com.talentboozt.s_backend.domains.edu.enums;

public enum EAIUsageType {
    COURSE_GENERATION,
    COURSE_OUTLINE_GENERATION,
    COURSE_CONTENT_GENERATION,
    COURSE_QUIZ_GENERATION,
    COURSE_SUMMARY_GENERATION,
    COURSE_TRANSLATION,
    COURSE_REWRITE,
    COURSE_REVISION,
    COURSE_VALIDATION,
    COURSE_OTHER
}
